### ISSUE TITLE
Bug in evaluation code

### ISSUE THREAD

**Issue by trinhxuankhai** [woven-visionai/wts-dataset#7]
From lines 143 to 146 of code evaluation/eval-metrics-AIC-Track2/metrics_all.py, if I do not submit the result to a specific sample, this section of code states that that sample will count zero, but it should also increment the num_segments_overall, or that sample will be skipped and the evaluation code can be bypassed by submitting only serveral sample with the best score.
![image](https://github.com/woven-visionai/wts-dataset/assets/64684468/13c50f13-ce3e-45c8-83e0-1e53a54a5990)

**Comment by woven-visionai** [comment]
Hello, thanks for pointing out this issue. We have already fixed it in our latest master. Please take another look.

**Comment by trinhxuankhai** [comment]
Will the evaluation system on the leaderboard be updated following the issue?
