### ISSUE TITLE
No tracked bbox in training  set

### ISSUE THREAD

**Issue by qingchunlizhi** [woven-visionai/wts-dataset#8]
Hi，
    As the readme shows that there are the  tracked bbox in the bbox_generated files, but we find the bbox_generated files in the training set is the same as the bbox_annotated files. Will you release the right bbox_generated files of traning set?
    Thanks!

**Comment by woven-visionai** [comment]
Hi thank you for sharing this.
we will update it, and currently, the vehicle view and normal view are correct for the generated bbox for use.
you could try them first.

**Comment by qingchunlizhi** [comment]
> Hi thank you for sharing this. we will update it, and currently, the vehicle view and normal view are correct for the generated bbox for use. you could try them first.

Where can I download the updated training set? thanks!

**Comment by woven-visionai** [comment]
the overhead view is still updating, for the vehicle view and normal view bbox annotation it is already in the annotation folder where you are accessing now.
